//! Order-Statistic Tree (treap-based).
//!
//! An **order-statistic tree** is a balanced binary search tree augmented with
//! per-node subtree-size counts.  The size augmentation allows two extra
//! operations beyond an ordinary BST:
//!
//! - [`OrderStatisticTree::select`] — return the `k`-th smallest key (0-indexed)
//!   in **O(log n)** expected time.
//! - [`OrderStatisticTree::rank`] — return the number of keys strictly less than
//!   a given key in **O(log n)** expected time.
//!
//! ## Balancing strategy
//!
//! Each node carries a random `u64` priority generated by an internal
//! xorshift-64 PRNG.  The tree maintains the **treap invariant**: BST order on
//! keys _and_ max-heap order on priorities.  Because priorities are uniformly
//! random, the expected depth of any node is O(log n), giving O(log n) expected
//! time for all operations.  The worst-case depth is O(n) but occurs with
//! vanishing probability.
//!
//! ## Complexity
//!
//! | Operation   | Expected | Worst-case |
//! |-------------|----------|------------|
//! | `insert`    | O(log n) | O(n)       |
//! | `remove`    | O(log n) | O(n)       |
//! | `contains`  | O(log n) | O(n)       |
//! | `select`    | O(log n) | O(n)       |
//! | `rank`      | O(log n) | O(n)       |
//! | `len`       | O(1)     | O(1)       |
//!
//! Space: O(n).
//!
//! ## Preconditions
//!
//! - Duplicate keys are rejected: [`OrderStatisticTree::insert`] returns
//!   `false` and does not modify the tree when the key is already present.
//! - All operations accept keys by reference where possible.

use std::cmp::Ordering;

/// Internal xorshift-64 PRNG — avoids pulling in the `rand` crate.
struct Xorshift64 {
    state: u64,
}

impl Xorshift64 {
    const fn new(seed: u64) -> Self {
        // Seed must not be zero; fold it to avoid a stuck zero state.
        let state = if seed == 0 {
            0x853c_49e6_748f_ea9b
        } else {
            seed
        };
        Self { state }
    }

    #[allow(clippy::missing_const_for_fn)]
    fn next(&mut self) -> u64 {
        // xorshift64 — period 2^64 - 1, simple and fast.
        self.state ^= self.state << 13;
        self.state ^= self.state >> 7;
        self.state ^= self.state << 17;
        self.state
    }
}

// ---------------------------------------------------------------------------
// Node
// ---------------------------------------------------------------------------

#[allow(clippy::use_self)] // field types cannot use `Self` in recursive structs
struct Node<K> {
    key: K,
    priority: u64,
    /// Number of nodes in this subtree (including this node).
    size: usize,
    left: Option<Box<Node<K>>>,
    right: Option<Box<Node<K>>>,
}

impl<K> Node<K> {
    #[allow(clippy::unnecessary_box_returns)]
    fn new(key: K, priority: u64) -> Box<Self> {
        Box::new(Self {
            key,
            priority,
            size: 1,
            left: None,
            right: None,
        })
    }
}

// `Box<T>` implements `Deref<Target = T>`, so `Option<Box<Node<K>>>` can be
// dereffed to `Option<&Node<K>>` via `.as_deref()`.

/// Return the subtree size (0 if the node is absent).
#[inline]
fn subtree_size<K>(node: Option<&Node<K>>) -> usize {
    node.map_or(0, |n| n.size)
}

/// Recompute `node.size` from its children.  Call after any structural change.
#[inline]
fn update_size<K>(node: &mut Box<Node<K>>) {
    node.size = 1 + subtree_size(node.left.as_deref()) + subtree_size(node.right.as_deref());
}

// ---------------------------------------------------------------------------
// Rotations
// ---------------------------------------------------------------------------

/// Right-rotate: the left child moves up.
///
/// ```text
///     node                 left
///    /    \               /    \
///  left   right   →    ll     node
///  /  \                       /  \
/// ll   lr                    lr  right
/// ```
/// Returns the new root of this subtree.
#[allow(clippy::unnecessary_box_returns)]
fn rotate_right<K>(mut node: Box<Node<K>>) -> Box<Node<K>> {
    let mut left = node
        .left
        .take()
        .expect("rotate_right requires a left child");
    node.left = left.right.take();
    update_size(&mut node);
    left.right = Some(node);
    update_size(&mut left);
    left
}

/// Left-rotate: the right child moves up.
#[allow(clippy::unnecessary_box_returns)]
fn rotate_left<K>(mut node: Box<Node<K>>) -> Box<Node<K>> {
    let mut right = node
        .right
        .take()
        .expect("rotate_left requires a right child");
    node.right = right.left.take();
    update_size(&mut node);
    right.left = Some(node);
    update_size(&mut right);
    right
}

// ---------------------------------------------------------------------------
// Recursive helpers
// ---------------------------------------------------------------------------

/// Insert `key` with `priority` into the subtree rooted at `root`.
/// Returns `(new_root, inserted)`.
fn insert_node<K: Ord>(
    root: Option<Box<Node<K>>>,
    key: K,
    priority: u64,
) -> (Option<Box<Node<K>>>, bool) {
    match root {
        None => (Some(Node::new(key, priority)), true),
        Some(mut node) => match key.cmp(&node.key) {
            Ordering::Equal => {
                // Duplicate — reject without modifying.
                (Some(node), false)
            }
            Ordering::Less => {
                let (new_left, inserted) = insert_node(node.left.take(), key, priority);
                node.left = new_left;
                update_size(&mut node);
                // Restore heap order: if left child has higher priority,
                // rotate right to bring it up.
                let mut root_node = node;
                if inserted
                    && root_node
                        .left
                        .as_deref()
                        .is_some_and(|l| l.priority > root_node.priority)
                {
                    root_node = rotate_right(root_node);
                }
                (Some(root_node), inserted)
            }
            Ordering::Greater => {
                let (new_right, inserted) = insert_node(node.right.take(), key, priority);
                node.right = new_right;
                update_size(&mut node);
                let mut root_node = node;
                if inserted
                    && root_node
                        .right
                        .as_deref()
                        .is_some_and(|r| r.priority > root_node.priority)
                {
                    root_node = rotate_left(root_node);
                }
                (Some(root_node), inserted)
            }
        },
    }
}

/// Remove the node with `key` from the subtree rooted at `root`.
/// Returns `(new_root, removed)`.
#[allow(clippy::option_if_let_else)]
fn remove_node<K: Ord>(root: Option<Box<Node<K>>>, key: &K) -> (Option<Box<Node<K>>>, bool) {
    match root {
        None => (None, false),
        Some(mut node) => match key.cmp(&node.key) {
            Ordering::Equal => {
                // Rotate the target down until it becomes a leaf, then drop.
                (rotate_down_and_remove(node), true)
            }
            Ordering::Less => {
                let (new_left, removed) = remove_node(node.left.take(), key);
                node.left = new_left;
                update_size(&mut node);
                (Some(node), removed)
            }
            Ordering::Greater => {
                let (new_right, removed) = remove_node(node.right.take(), key);
                node.right = new_right;
                update_size(&mut node);
                (Some(node), removed)
            }
        },
    }
}

/// Rotate `node` downward (toward the child with the higher priority) until it
/// has no children, then drop it, returning the new subtree root.
fn rotate_down_and_remove<K: Ord>(node: Box<Node<K>>) -> Option<Box<Node<K>>> {
    let left_pri = node.left.as_deref().map_or(0, |n| n.priority);
    let right_pri = node.right.as_deref().map_or(0, |n| n.priority);

    if left_pri == 0 && right_pri == 0 {
        // Node is a leaf — drop it.
        return None;
    }

    if left_pri >= right_pri {
        // Rotate right: left child moves up.
        let mut new_root = rotate_right(node);
        // The target is now the right child of new_root.
        let target = new_root
            .right
            .take()
            .expect("right child must exist after rotate_right");
        new_root.right = rotate_down_and_remove(target);
        update_size(&mut new_root);
        Some(new_root)
    } else {
        // Rotate left: right child moves up.
        let mut new_root = rotate_left(node);
        let target = new_root
            .left
            .take()
            .expect("left child must exist after rotate_left");
        new_root.left = rotate_down_and_remove(target);
        update_size(&mut new_root);
        Some(new_root)
    }
}

/// `select(k)` — return a reference to the k-th smallest key (0-indexed).
fn select_node<K>(root: Option<&Node<K>>, k: usize) -> Option<&K> {
    let node = root?;
    let left_size = subtree_size(node.left.as_deref());
    match k.cmp(&left_size) {
        Ordering::Equal => Some(&node.key),
        Ordering::Less => select_node(node.left.as_deref(), k),
        Ordering::Greater => select_node(node.right.as_deref(), k - left_size - 1),
    }
}

/// `rank(key)` — number of keys strictly less than `key`.
fn rank_node<K: Ord>(root: Option<&Node<K>>, key: &K) -> usize {
    root.map_or(0, |node| match key.cmp(&node.key) {
        Ordering::Less => rank_node(node.left.as_deref(), key),
        Ordering::Equal => subtree_size(node.left.as_deref()),
        Ordering::Greater => {
            1 + subtree_size(node.left.as_deref()) + rank_node(node.right.as_deref(), key)
        }
    })
}

/// `contains(key)` — BST search.
fn contains_node<K: Ord>(root: Option<&Node<K>>, key: &K) -> bool {
    root.is_some_and(|node| match key.cmp(&node.key) {
        Ordering::Equal => true,
        Ordering::Less => contains_node(node.left.as_deref(), key),
        Ordering::Greater => contains_node(node.right.as_deref(), key),
    })
}

// ---------------------------------------------------------------------------
// Public struct
// ---------------------------------------------------------------------------

/// Order-Statistic Tree backed by a randomised treap.
///
/// Supports `select(k)` (k-th smallest, 0-indexed) and `rank(key)` (number of
/// keys strictly less than `key`) in O(log n) expected time, alongside the
/// standard `insert`, `remove`, and `contains` operations.
///
/// Duplicate keys are rejected: `insert` returns `false` and leaves the tree
/// unchanged when the key is already present.
pub struct OrderStatisticTree<K: Ord> {
    root: Option<Box<Node<K>>>,
    rng: Xorshift64,
}

impl<K: Ord> OrderStatisticTree<K> {
    /// Create an empty tree using a default internal seed.
    pub const fn new() -> Self {
        Self {
            root: None,
            // A well-spread constant seed (not zero, not all-ones).
            rng: Xorshift64::new(0x517c_c1b7_2722_0a95),
        }
    }

    /// Create an empty tree with a fixed seed for the internal PRNG.
    ///
    /// Use this constructor when you need deterministic behaviour (e.g. in
    /// tests).  All structural guarantees are unchanged; the seed merely
    /// controls which priorities are assigned to nodes.
    pub const fn with_seed(seed: u64) -> Self {
        Self {
            root: None,
            rng: Xorshift64::new(seed),
        }
    }

    /// Insert `key` into the tree.
    ///
    /// Returns `true` if the key was newly inserted, or `false` if it was
    /// already present (duplicates are rejected; the tree is not modified).
    pub fn insert(&mut self, key: K) -> bool {
        let priority = self.rng.next();
        let (new_root, inserted) = insert_node(self.root.take(), key, priority);
        self.root = new_root;
        inserted
    }

    /// Return `true` if `key` is present in the tree.
    pub fn contains(&self, key: &K) -> bool {
        contains_node(self.root.as_deref(), key)
    }

    /// Remove `key` from the tree.
    ///
    /// Returns `true` if the key was found and removed, `false` if it was
    /// absent.
    pub fn remove(&mut self, key: &K) -> bool {
        let (new_root, removed) = remove_node(self.root.take(), key);
        self.root = new_root;
        removed
    }

    /// Return a reference to the `k`-th smallest key (0-indexed).
    ///
    /// Returns `None` if `k >= self.len()`.
    #[must_use]
    pub fn select(&self, k: usize) -> Option<&K> {
        select_node(self.root.as_deref(), k)
    }

    /// Return the number of keys in the tree that are strictly less than
    /// `key`.
    ///
    /// If `key` is less than every key in the tree, returns 0.  If `key` is
    /// greater than every key, returns `self.len()`.
    #[must_use]
    pub fn rank(&self, key: &K) -> usize {
        rank_node(self.root.as_deref(), key)
    }

    /// Number of keys currently stored in the tree.
    #[must_use]
    pub fn len(&self) -> usize {
        subtree_size(self.root.as_deref())
    }

    /// Return `true` if the tree contains no keys.
    #[must_use]
    pub const fn is_empty(&self) -> bool {
        self.root.is_none()
    }
}

impl<K: Ord> Default for OrderStatisticTree<K> {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::OrderStatisticTree;
    use quickcheck::TestResult;
    use quickcheck_macros::quickcheck;

    // -----------------------------------------------------------------------
    // Empty-tree invariants
    // -----------------------------------------------------------------------

    #[test]
    fn empty_tree_len_is_zero() {
        let t: OrderStatisticTree<i32> = OrderStatisticTree::new();
        assert_eq!(t.len(), 0);
        assert!(t.is_empty());
    }

    #[test]
    fn empty_tree_select_is_none() {
        let t: OrderStatisticTree<i32> = OrderStatisticTree::new();
        assert_eq!(t.select(0), None);
        assert_eq!(t.select(100), None);
    }

    #[test]
    fn empty_tree_rank_is_zero() {
        let t: OrderStatisticTree<i32> = OrderStatisticTree::new();
        assert_eq!(t.rank(&42), 0);
    }

    // -----------------------------------------------------------------------
    // Insert / contains
    // -----------------------------------------------------------------------

    #[test]
    fn insert_and_contains() {
        let mut t = OrderStatisticTree::new();
        assert!(t.insert(5));
        assert!(t.insert(3));
        assert!(t.insert(7));
        assert!(t.contains(&5));
        assert!(t.contains(&3));
        assert!(t.contains(&7));
        assert!(!t.contains(&0));
        assert!(!t.contains(&99));
        assert_eq!(t.len(), 3);
    }

    #[test]
    fn duplicate_insert_returns_false_and_len_unchanged() {
        let mut t = OrderStatisticTree::new();
        assert!(t.insert(10));
        assert_eq!(t.len(), 1);
        assert!(!t.insert(10));
        assert_eq!(t.len(), 1);
        assert!(!t.insert(10));
        assert_eq!(t.len(), 1);
    }

    // -----------------------------------------------------------------------
    // Remove
    // -----------------------------------------------------------------------

    #[test]
    fn remove_present_returns_true() {
        let mut t = OrderStatisticTree::new();
        t.insert(4);
        t.insert(2);
        t.insert(6);
        assert!(t.remove(&2));
        assert_eq!(t.len(), 2);
        assert!(!t.contains(&2));
    }

    #[test]
    fn remove_absent_returns_false() {
        let mut t = OrderStatisticTree::new();
        t.insert(4);
        assert!(!t.remove(&99));
        assert_eq!(t.len(), 1);
    }

    #[test]
    fn remove_all_until_empty() {
        let mut t = OrderStatisticTree::new();
        for k in [1, 2, 3, 4, 5] {
            t.insert(k);
        }
        for k in [3, 1, 5, 2, 4] {
            assert!(t.remove(&k));
        }
        assert!(t.is_empty());
        assert_eq!(t.len(), 0);
    }

    // -----------------------------------------------------------------------
    // select
    // -----------------------------------------------------------------------

    #[test]
    fn select_first_and_last() {
        let mut t = OrderStatisticTree::new();
        for k in [5, 3, 8, 1, 9, 2, 7, 4, 6] {
            t.insert(k);
        }
        assert_eq!(t.select(0), Some(&1));
        assert_eq!(t.select(t.len() - 1), Some(&9));
    }

    #[test]
    fn select_out_of_bounds_is_none() {
        let mut t = OrderStatisticTree::new();
        t.insert(1);
        t.insert(2);
        assert_eq!(t.select(2), None);
        assert_eq!(t.select(100), None);
    }

    #[test]
    fn select_sequential() {
        let keys = [5, 1, 9, 3, 7, 2, 8, 4, 6];
        let mut t = OrderStatisticTree::new();
        for &k in &keys {
            t.insert(k);
        }
        let mut sorted = keys.to_vec();
        sorted.sort_unstable();
        for (k, &expected) in sorted.iter().enumerate() {
            assert_eq!(t.select(k), Some(&expected), "select({k}) failed");
        }
    }

    // -----------------------------------------------------------------------
    // rank
    // -----------------------------------------------------------------------

    #[test]
    fn rank_present_keys() {
        let mut t = OrderStatisticTree::new();
        for k in [1, 3, 5, 7, 9] {
            t.insert(k);
        }
        assert_eq!(t.rank(&1), 0);
        assert_eq!(t.rank(&3), 1);
        assert_eq!(t.rank(&5), 2);
        assert_eq!(t.rank(&7), 3);
        assert_eq!(t.rank(&9), 4);
    }

    #[test]
    fn rank_absent_keys() {
        let mut t = OrderStatisticTree::new();
        for k in [10, 20, 30] {
            t.insert(k);
        }
        // Before minimum
        assert_eq!(t.rank(&5), 0);
        // Between 10 and 20
        assert_eq!(t.rank(&15), 1);
        // After maximum
        assert_eq!(t.rank(&35), 3);
    }

    // -----------------------------------------------------------------------
    // Deterministic seed
    // -----------------------------------------------------------------------

    #[test]
    fn with_seed_deterministic_ordering() {
        let keys = [42, 7, 99, 3, 55, 18, 71, 1, 88, 34];
        let mut t = OrderStatisticTree::with_seed(42);
        for &k in &keys {
            t.insert(k);
        }
        let mut sorted = keys.to_vec();
        sorted.sort_unstable();

        // select and rank must agree on the sorted order.
        for (idx, &key) in sorted.iter().enumerate() {
            assert_eq!(t.select(idx), Some(&key), "select({idx}) expected {key}");
            assert_eq!(t.rank(&key), idx, "rank({key}) expected {idx}");
        }
    }

    // -----------------------------------------------------------------------
    // Property test
    // -----------------------------------------------------------------------

    /// For a deduplicated, sorted Vec<i32> inserted into the tree:
    /// - `tree.select(k)` matches `sorted[k]` for every valid `k`.
    /// - `tree.rank(&q)` equals the number of elements in `sorted` that are
    ///   strictly less than `q`, checked for every element in `sorted`.
    #[quickcheck]
    #[allow(clippy::needless_pass_by_value)]
    fn prop_select_and_rank_agree_with_sorted_vec(values: Vec<i32>) -> TestResult {
        if values.len() > 200 {
            return TestResult::discard();
        }

        // Build deduplicated sorted reference.
        let mut sorted = values;
        sorted.sort_unstable();
        sorted.dedup();

        let mut t = OrderStatisticTree::with_seed(0xdead_beef);
        for &v in &sorted {
            t.insert(v);
        }

        // Check select.
        for (k, &expected) in sorted.iter().enumerate() {
            if t.select(k) != Some(&expected) {
                return TestResult::failed();
            }
        }

        // select out of bounds.
        if t.select(sorted.len()).is_some() {
            return TestResult::failed();
        }

        // Check rank for every key present.
        for &q in &sorted {
            let expected_rank = sorted.iter().filter(|&&x| x < q).count();
            if t.rank(&q) != expected_rank {
                return TestResult::failed();
            }
        }

        TestResult::passed()
    }
}
