//! Solovay-Strassen probabilistic primality test.
//!
//! Built on the Euler-Jacobi congruence: for any odd prime `n` and any
//! integer `a` coprime to `n`,
//!
//! ```text
//! a^((n-1)/2) ≡ Jacobi(a, n) (mod n).
//! ```
//!
//! For composite `n` the congruence fails for at least half of the
//! integers `a` in `[1, n)`, so each round of testing halves the worst-case
//! probability that a composite slips through. After `k` rounds the false
//! positive rate is at most `2^-k`.
//!
//! Witnesses are produced by a small linear congruential generator seeded
//! from `n`, which keeps results deterministic and reproducible without
//! pulling in a `rand` dependency. All modular products go through `u128`
//! so any `n` that fits in `u64` is safe from overflow.
//!
//! - Time: `O(k · log^2 n)` for `k` rounds.
//! - Space: `O(1)`.

use crate::math::modular_exponentiation::mod_pow;

/// Computes the Jacobi symbol `(a / n)` using the standard quadratic
/// reciprocity reduction. `n` must be odd and positive; the function
/// returns `-1`, `0`, or `+1`.
///
/// The Jacobi symbol generalises the Legendre symbol to odd composite
/// moduli. When `n` is prime it equals the Legendre symbol and so reports
/// quadratic residuosity directly; for composite `n` it is still a useful
/// algebraic quantity but no longer characterises residues.
///
/// - Time: `O(log min(|a|, n))`.
/// - Space: `O(1)`.
pub fn jacobi(a: i64, n: u64) -> i8 {
    assert!(n > 0 && !n.is_multiple_of(2), "n must be odd and positive");
    // Reduce a modulo n into [0, n).
    let mut a = a.rem_euclid(n as i64) as u64;
    let mut n = n;
    let mut result: i8 = 1;
    while a != 0 {
        // Pull out factors of two: (2 / n) = +1 if n ≡ ±1 (mod 8), else -1.
        while a.is_multiple_of(2) {
            a /= 2;
            let r = n % 8;
            if r == 3 || r == 5 {
                result = -result;
            }
        }
        // Quadratic reciprocity flip; sign changes when both ≡ 3 (mod 4).
        std::mem::swap(&mut a, &mut n);
        if a % 4 == 3 && n % 4 == 3 {
            result = -result;
        }
        a %= n;
    }
    if n == 1 {
        result
    } else {
        0
    }
}

/// Returns `true` if `n` is judged prime by `k` rounds of Solovay-Strassen.
///
/// The witness sequence is generated by a deterministic LCG seeded from
/// `n`, so the result is reproducible across runs and platforms. `n <= 1`
/// is rejected directly and `n == 2` is accepted directly.
///
/// - Time: `O(k · log^2 n)`.
/// - Space: `O(1)`.
pub fn is_prime_solovay_strassen(n: u64, k: u32) -> bool {
    if n < 2 {
        return false;
    }
    if n == 2 {
        return true;
    }
    if n.is_multiple_of(2) {
        return false;
    }
    // n == 3 is prime; the witness range [2, n-2] is empty so handle here.
    if n == 3 {
        return true;
    }

    // Numerical Recipes LCG; period 2^64. Seeded from n so the result is
    // deterministic. The seed mixes n with a constant offset to avoid the
    // degenerate `state == 0` case when n itself is small.
    let mut state: u64 = n.wrapping_mul(6_364_136_223_846_793_005).wrapping_add(1);
    let exp = (n - 1) / 2;

    for _ in 0..k {
        // Advance the LCG and pick a witness uniformly in [2, n-2].
        state = state
            .wrapping_mul(6_364_136_223_846_793_005)
            .wrapping_add(1_442_695_040_888_963_407);
        let a = 2 + (state % (n - 3));

        let j = jacobi(a as i64, n);
        if j == 0 {
            // gcd(a, n) > 1, so n is composite.
            return false;
        }
        // Reduce Jacobi symbol modulo n: -1 maps to n - 1.
        let j_mod = if j == -1 { n - 1 } else { 1 };
        let r = mod_pow(a, exp, n);
        if r != j_mod {
            return false;
        }
    }
    true
}

#[cfg(test)]
mod tests {
    use super::{is_prime_solovay_strassen, jacobi};

    /// Trial-division reference up to `n`'s square root. Used as ground
    /// truth in cross-checks below; deliberately self-contained so the
    /// test does not depend on any other module.
    fn is_prime_trial(n: u64) -> bool {
        if n < 2 {
            return false;
        }
        if n < 4 {
            return true;
        }
        if n.is_multiple_of(2) {
            return false;
        }
        let mut p: u64 = 3;
        while p.saturating_mul(p) <= n {
            if n.is_multiple_of(p) {
                return false;
            }
            p += 2;
        }
        true
    }

    #[test]
    fn jacobi_small_table() {
        assert_eq!(jacobi(1, 1), 1);
        assert_eq!(jacobi(2, 3), -1);
        assert_eq!(jacobi(2, 5), -1);
        assert_eq!(jacobi(3, 5), -1);
        assert_eq!(jacobi(2, 7), 1);
        assert_eq!(jacobi(7, 15), -1);
        assert_eq!(jacobi(0, 1), 1);
    }

    #[test]
    fn jacobi_zero_when_not_coprime() {
        // gcd(a, n) > 1 must produce 0.
        assert_eq!(jacobi(3, 9), 0);
        assert_eq!(jacobi(5, 15), 0);
        assert_eq!(jacobi(6, 21), 0);
    }

    #[test]
    #[should_panic(expected = "n must be odd and positive")]
    fn jacobi_even_n_panics() {
        let _ = jacobi(1, 4);
    }

    #[test]
    #[should_panic(expected = "n must be odd and positive")]
    fn jacobi_zero_n_panics() {
        let _ = jacobi(1, 0);
    }

    #[test]
    fn small_primes_accepted() {
        for &p in &[2_u64, 3, 5, 7, 11, 13, 17, 19, 23, 29] {
            assert!(is_prime_solovay_strassen(p, 20), "{p} should be prime");
        }
    }

    #[test]
    fn small_composites_rejected() {
        for &c in &[4_u64, 6, 8, 9, 15, 21, 25, 27, 33] {
            assert!(!is_prime_solovay_strassen(c, 20), "{c} should be composite");
        }
    }

    #[test]
    fn carmichael_561_rejected() {
        // 561 = 3 · 11 · 17. Fools Fermat's test for every coprime base
        // but Solovay-Strassen rejects it with probability ≥ 1 - 2^-20.
        assert!(!is_prime_solovay_strassen(561, 20));
    }

    #[test]
    fn zero_and_one_rejected() {
        assert!(!is_prime_solovay_strassen(0, 20));
        assert!(!is_prime_solovay_strassen(1, 20));
    }

    #[test]
    fn matches_trial_division_up_to_10000() {
        for n in 0..10_000_u64 {
            let expected = is_prime_trial(n);
            let got = is_prime_solovay_strassen(n, 20);
            assert_eq!(got, expected, "mismatch at n={n}");
        }
    }
}
